In [2]:
import pandas as pd

# Load data from CSV file
df = pd.read_csv("bonus_dataset.csv")
df.head()

,employee_id,performance,years_of_experience,projects_completed,bonus
0,EMP_001,7,2,4,124
1,EMP_002,4,1,4,82
2,EMP_003,8,7,10,178
3,EMP_004,5,7,8,138
4,EMP_005,7,8,9,170


In [3]:
from sklearn.model_selection import train_test_split

# Separate features and target
X = df[['performance', 'years_of_experience', 'projects_completed']].values
y = df[['bonus']].values  # Ensure target is a 2D array for compatibility

# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [4]:
import torch
import torch.nn as nn
import torch.optim as optim

# Seed for reproducibility
torch.manual_seed(0)

# Convert to PyTorch tensors
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test, dtype=torch.float32)

In [5]:
class BonusPredictor(nn.Module):
    def __init__(self):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(3, 1),  # 3 input features -> 1 output neuron
        )

    def forward(self, x):
        return self.network(x)

In [6]:
model = BonusPredictor()
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.005)

In [7]:
# Training loop
epochs = 5000
for epoch in range(epochs):
    # Forward pass: Compute predicted bonus by passing X_train
    predictions = model(X_train_tensor)
    loss = criterion(predictions, y_train_tensor)

    # Backward pass: Compute gradients
    optimizer.zero_grad()
    loss.backward()

    # Update parameters
    optimizer.step()

    # Print loss every 100 epochs
    if (epoch + 1) % 100 == 0:
        print(f"Epoch [{epoch + 1}/{epochs}], Loss: {loss.item():.2f}")

Epoch [100/5000], Loss: 19.62
Epoch [200/5000], Loss: 17.46
Epoch [300/5000], Loss: 15.56
Epoch [400/5000], Loss: 13.88
Epoch [500/5000], Loss: 12.38
Epoch [600/5000], Loss: 11.05
Epoch [700/5000], Loss: 9.86
Epoch [800/5000], Loss: 8.80
Epoch [900/5000], Loss: 7.85
Epoch [1000/5000], Loss: 7.01
Epoch [1100/5000], Loss: 6.25
Epoch [1200/5000], Loss: 5.58
Epoch [1300/5000], Loss: 4.98
Epoch [1400/5000], Loss: 4.44
Epoch [1500/5000], Loss: 3.96
Epoch [1600/5000], Loss: 3.54
Epoch [1700/5000], Loss: 3.16
Epoch [1800/5000], Loss: 2.82
Epoch [1900/5000], Loss: 2.51
Epoch [2000/5000], Loss: 2.24
Epoch [2100/5000], Loss: 2.00
Epoch [2200/5000], Loss: 1.79
Epoch [2300/5000], Loss: 1.59
Epoch [2400/5000], Loss: 1.42
Epoch [2500/5000], Loss: 1.27
Epoch [2600/5000], Loss: 1.13
Epoch [2700/5000], Loss: 1.01
Epoch [2800/5000], Loss: 0.90
Epoch [2900/5000], Loss: 0.81
Epoch [3000/5000], Loss: 0.72
Epoch [3100/5000], Loss: 0.64
Epoch [3200/5000], Loss: 0.57
Epoch [3300/5000], Loss: 0.51
Epoch [3400/5

In [8]:
model.eval()

with torch.no_grad():
    test_predictions = model(X_test_tensor)
    test_loss = criterion(test_predictions, y_test_tensor)
    print(f"Test Loss: {test_loss.item():.2f}")

Test Loss: 0.07


In [9]:
X_test_tensor[:3]

tensor([[10.,  4.,  7.],
        [ 3.,  5.,  8.],
        [ 8.,  7., 10.]])

In [10]:
test_predictions[:3]

tensor([[178.3009],
        [102.0224],
        [178.3721]])

In [11]:
y_test_tensor[:3]

tensor([[178.],
        [102.],
        [178.]])

In [12]:
for name, value in model.named_parameters():
    print(f"Name: {name}, Value: {value}")

Name: network.0.weight, Value: Parameter containing:
tensor([[12.0477,  5.8225,  2.2331]], requires_grad=True)
Name: network.0.bias, Value: Parameter containing:
tensor([18.9024], requires_grad=True)
