In [77]:
import torch
import pandas as pd
from matplotlib import pyplot as plt

df = pd.read_csv('bonus_dataset.csv')
df.head()

,employee_id,performance,years_of_experience,projects_completed,bonus
0,EMP_001,7,2,4,124
1,EMP_002,4,1,4,82
2,EMP_003,8,7,10,178
3,EMP_004,5,7,8,138
4,EMP_005,7,8,9,170


In [33]:
df.shape

(100, 5)

In [34]:
import torch

# Extract features and target from the DataFrame
performance = torch.tensor(df['performance'].values, dtype=torch.float32)
years_of_experience = torch.tensor(df['years_of_experience'].values, dtype=torch.float32)
projects_completed = torch.tensor(df['projects_completed'].values, dtype=torch.float32)
bonus = torch.tensor(df['bonus'].values, dtype=torch.float32)

In [49]:
w1=torch.rand(1, requires_grad=True)
w2=torch.rand(1, requires_grad=True)
w3=torch.rand(1, requires_grad=True)
b=torch.rand(1, requires_grad=True)

w1 ,w2 ,w3 ,b

(tensor([0.9576], requires_grad=True),
 tensor([0.8719], requires_grad=True),
 tensor([0.8830], requires_grad=True),
 tensor([0.7357], requires_grad=True))

In [52]:
learning_rate = 0.007
for epoch in range(8000):
    # Forward pass: Compute predicted bonus
    predicted_bonus = w1 * performance + w2 * years_of_experience + w3 * projects_completed + b
    
    # Compute loss (Mean Squared Error)
    loss = torch.mean((predicted_bonus - bonus) ** 2)
    
    # Backward pass: Compute gradients
    loss.backward()
    
    # Update weights and bias using gradient descent
    with torch.no_grad():
        w1 -= learning_rate * w1.grad
        w2 -= learning_rate * w2.grad
        w3 -= learning_rate * w3.grad
        b -= learning_rate * b.grad
        
        # Zero the gradients after updating
        w1.grad.zero_()
        w2.grad.zero_()
        w3.grad.zero_()
        b.grad.zero_()

        if  epoch % 100 == 0:
            print(f'Epoch {epoch}, Loss: {loss.item():.2f}')  

Epoch 0, Loss: 4.05
Epoch 100, Loss: 3.46
Epoch 200, Loss: 2.95
Epoch 300, Loss: 2.52
Epoch 400, Loss: 2.15
Epoch 500, Loss: 1.83
Epoch 600, Loss: 1.56
Epoch 700, Loss: 1.33
Epoch 800, Loss: 1.14
Epoch 900, Loss: 0.97
Epoch 1000, Loss: 0.83
Epoch 1100, Loss: 0.71
Epoch 1200, Loss: 0.60
Epoch 1300, Loss: 0.51
Epoch 1400, Loss: 0.44
Epoch 1500, Loss: 0.37
Epoch 1600, Loss: 0.32
Epoch 1700, Loss: 0.27
Epoch 1800, Loss: 0.23
Epoch 1900, Loss: 0.20
Epoch 2000, Loss: 0.17
Epoch 2100, Loss: 0.14
Epoch 2200, Loss: 0.12
Epoch 2300, Loss: 0.11
Epoch 2400, Loss: 0.09
Epoch 2500, Loss: 0.08
Epoch 2600, Loss: 0.07
Epoch 2700, Loss: 0.06
Epoch 2800, Loss: 0.05
Epoch 2900, Loss: 0.04
Epoch 3000, Loss: 0.03
Epoch 3100, Loss: 0.03
Epoch 3200, Loss: 0.03
Epoch 3300, Loss: 0.02
Epoch 3400, Loss: 0.02
Epoch 3500, Loss: 0.02
Epoch 3600, Loss: 0.01
Epoch 3700, Loss: 0.01
Epoch 3800, Loss: 0.01
Epoch 3900, Loss: 0.01
Epoch 4000, Loss: 0.01
Epoch 4100, Loss: 0.01
Epoch 4200, Loss: 0.01
Epoch 4300, Loss: 0.00


In [53]:
w1.item(), w2.item(), w3.item(), b.item()

(12.000639915466309, 5.997808933258057, 2.0029244422912598, 19.98571014404297)